# CGT 290 Week4
## Python Tutorial: Numpy

### Feb, 5
Zongcheng Chu

## What is Numpy?

**Numpy** is a general-purpose array-processing package. It provides a high-performance multidimensional array object, and tools for working with these arrays. It is the fundamental package for scientific computing with Python.

In [1]:
# import numpy library in Python
import numpy

In [2]:
# what people usually do is to rename it for the purpose of easy-to-use.
import numpy as np

In [3]:
# let's first make an 1-d array
a1 = np.array([1,2,3])
print(a1)
print(a1.shape)

[1 2 3]
(3,)


In [4]:
# again, we create another 2d array (two pairs of brackets)
a2 = np.array([[1,2,3],[4,5,6]])
print(a2)
print(a2.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [6]:
# let's see what data type is in numpy
print(type(a1))
print(type(a2))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


### list and numpy array are convertable

In [10]:
l1=[1,2,3,4,5] 
print (type(l1)) 

<class 'list'>


In [12]:
l2=np.array(l1) 
print(l2)
print (type(l2))
print(l2.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [14]:
l3=list(l2) # ndarray to Python list 
print (type(l3)) 
print(l3)

<class 'list'>
[1, 2, 3, 4, 5]


### Create numpy array(s) more efficiently

In [21]:
arr = np.arange(15)
arr
# range(0,15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [22]:
np.arange(2,3,0.1)   #start, end, step

array([2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9])

In [24]:
# numpy.linspace(start, stop, num = 50) : 
# Returns number spaces evenly w.r.t interval

np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [31]:
# create 2d array

arr1 = np.array([np.arange(10),np.arange(10)])

arr2 = np.array((range(10),range(10)))

print(arr1)
print("-"*30)
print(arr2)

[[0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]]
------------------------------
[[0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]]


### empty array

In [32]:
np.empty((6,6)) # specify the shape

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        7.48890956e-313, 2.61054848e+106, 0.00000000e+000],
       [            nan, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 8.94178787e-312, 8.94178787e-312,
        8.94178787e-312, 8.94178787e-312, 8.94178787e-312],
       [8.91238232e-313, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [2.11377150e-314, 1.26480805e-321, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000]])

### Diagonal matrix

In [34]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Random Matrix

In [36]:
#Create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1).

np.random.rand(3,2)

array([[0.85555323, 0.68603628],
       [0.71932746, 0.92077234],
       [0.27001414, 0.8780718 ]])

### Shuffle matrix

In [37]:
arr = np.arange(10)
np.random.shuffle(arr)
arr

array([4, 5, 7, 2, 9, 1, 6, 0, 3, 8])

### All 0 and All 1 matrix

In [38]:
z1= np.zeros((2,3)) # define the shape 
o1= np.ones((5,7))   # define the shape

print(z1)
print("-"*30)
print(o1)

[[0. 0. 0.]
 [0. 0. 0.]]
------------------------------
[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


### np.ones_like()

In [40]:
a = np.array([[1,2,3],[4,5,6]])  # shape: 2 * 3

np.ones_like(a)

array([[1, 1, 1],
       [1, 1, 1]])

### size

In [43]:
arr = np.array((np.arange(100),np.arange(100)))

arr.size

200

### numpy calculation

In [46]:
# add (element-wise)

x = np.array([[1,2,3],[4,5,6]])
y = np.array([[1,1,1],[1,1,1]])

# 1
print(x+y)

print("-"*30)

# 2
print(np.add(x,y))

[[2 3 4]
 [5 6 7]]
------------------------------
[[2 3 4]
 [5 6 7]]


In [47]:
# subtraction
x = np.array([[1,2,3],[4,5,6]])
y = np.array([[1,1,1],[1,1,1]])

# 1
print(x-y)

print("-"*30)

# 2
print(np.subtract(x,y))

[[0 1 2]
 [3 4 5]]
------------------------------
[[0 1 2]
 [3 4 5]]


In [49]:
# multiply
x = np.array([[1,2,3],[4,5,6]])
y = np.array([[2,2,2],[2,2,2]])

# 1
print(x*y)

print("-"*30)

# 2
print(np.multiply(x,y))

[[ 2  4  6]
 [ 8 10 12]]
------------------------------
[[ 2  4  6]
 [ 8 10 12]]


In [50]:
# divide
x = np.array([[1,2,3],[4,5,6]])
y = np.array([[2,2,2],[2,2,2]])

# 1
print(x/y)

print("-"*30)

# 2
print(np.divide(x,y))

[[0.5 1.  1.5]
 [2.  2.5 3. ]]
------------------------------
[[0.5 1.  1.5]
 [2.  2.5 3. ]]


### Matrix Multiplication 

In [53]:
# vector inner product
v1 = np.array([9,10])
v2 = np.array([10,11])

v1.dot(v2)

#or

np.dot(v1,v2)

200

In [54]:
# Matrix Multiplication
x=np.array([[1,2],[3,4]]) 
y=np.array([[5,6],[7,8]]) 

np.dot(x,y)

array([[19, 22],
       [43, 50]])

### Numpy slicing operation

In [55]:
# create an array

a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [58]:
# two dimension slicing (row and column)


# first ':' means all the rows, second ":" means all the columns
a[:,:]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [61]:
# the row with index 1 to the last row
# the column with index 1 to the last column
a[1:,1:]

array([[ 6,  7,  8],
       [10, 11, 12]])

In [62]:
a[2:,0:]

array([[ 9, 10, 11, 12]])

In [64]:
a[:2,:3]

array([[1, 2, 3],
       [5, 6, 7]])

### slicing by index

In [65]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [66]:
a[[0],[0,2]]

array([1, 3])

In [74]:
a[[0,2],0:3]

array([[ 1,  2,  3],
       [ 9, 10, 11]])

### filtering

In [72]:
bool_a = a > 2 
bool_a 

array([[False, False,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [73]:
a[bool_a]

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

### for loop

In [75]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [77]:
for row in a:
    print(i)
    print("-"*30)

[ 9 10 11 12]
------------------------------
[ 9 10 11 12]
------------------------------
[ 9 10 11 12]
------------------------------


In [78]:
for row in a:
    for x in row:
        print(x)

1
2
3
4
5
6
7
8
9
10
11
12


### operations on dimension

In [79]:
arr = np.arange(16)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [81]:
arr = arr.reshape(2,8)
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [82]:
arr = arr.reshape(2,2,4)
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [84]:
# transpose

a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [85]:
a.transpose()

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [86]:
v1 = np.array([1,2,3])
v1

array([1, 2, 3])

In [87]:
v1.transpose()

array([1, 2, 3])

### concat two arrays

In [89]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[1,1,1],[1,1,1]])

np.hstack([arr1,arr2])

array([[1, 2, 3, 1, 1, 1],
       [4, 5, 6, 1, 1, 1]])

In [90]:
np.vstack([arr1,arr2])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 1, 1],
       [1, 1, 1]])

### statistics

In [91]:
x=np.array([[1,2],[3,4]]) 
print(x)

[[1 2]
 [3 4]]


In [92]:
print("sum:",np.sum(x))
print("mean:",np.mean(x))
print("max:",np.max(x))
print("min:",np.min(x))

sum: 10
mean: 2.5
max: 4
min: 1


axis = 0 means we operate on the row level <br>
axis = 1 means we operate on the column level

In [95]:
x=np.array([[1,2],[3,4]]) 
print(x) 
print('----------') 
print('axis=0:',np.sum(x,axis=0)) 
print('axis=1:',np.sum(x,axis=1)) 

[[1 2]
 [3 4]]
----------
axis=0: [4 6]
axis=1: [3 7]


### sorting

In [98]:
# 1d

arr1 = np.random.rand(8)
arr1.sort()
arr1

array([0.0316592 , 0.41351305, 0.45476024, 0.50295223, 0.6902115 ,
       0.73176935, 0.83277653, 0.91513199])

In [99]:
# 2d

arr2 = np.random.rand(3,5)
arr2

array([[0.26645875, 0.37582835, 0.20426506, 0.57433423, 0.82471879],
       [0.44904861, 0.45827905, 0.42719912, 0.80196122, 0.9500699 ],
       [0.77007709, 0.02476328, 0.78402634, 0.49861203, 0.24604084]])

In [101]:
arr2.sort(axis=0)# row level
arr2

array([[0.26645875, 0.02476328, 0.20426506, 0.49861203, 0.24604084],
       [0.44904861, 0.37582835, 0.42719912, 0.57433423, 0.82471879],
       [0.77007709, 0.45827905, 0.78402634, 0.80196122, 0.9500699 ]])

In [103]:
arr2.sort(axis=1)
arr2

array([[0.02476328, 0.20426506, 0.24604084, 0.26645875, 0.49861203],
       [0.37582835, 0.42719912, 0.44904861, 0.57433423, 0.82471879],
       [0.45827905, 0.77007709, 0.78402634, 0.80196122, 0.9500699 ]])

### numpy input and output

In [104]:
#1. save array

a1=np.arange(50).reshape(2,5,5) 
np.save('a1.npy',a1)

In [105]:
#2. load array
a2 = np.load('a1.npy') 
a2

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]],

       [[25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]]])